### ISSUE TITLE
ADT aware response

### ISSUE THREAD

**Issue by jkanche** [LTLA/bakana#20]
- [x] preflight should include ADT aware response
  - [x] `adt_normalization` (would send size factors at some point)

**Comment by LTLA** [comment]
New preflight response structure looks like:

```js
    {
      annotations: { default: [ 'AAACCTGAGACCACGA-1' ] },
      features: {
        RNA: { fields: [Object], common: 33538 },
        ADT: { fields: [Object], common: 17 }
      }
    }
```

`fields` define the chosen fields for each modality, `common` defines the number of common features.
