### ISSUE TITLE
Proposed new strategy for handling saving and loading

### ISSUE THREAD

**Issue by LTLA** [LTLA/bakana#52]
The current approach is straining at the seams because it doesn't fully reconstitute the state. The current HDF5 state file is really only useful for the current version of the **kana** UI, as it only holds the statistics needed by the UI; this is not generalizable to other applications, nor will it work for future versions of the UI that need more information.

Here, I propose a shift to how we think about saving and loading. The first component of this shift involves reducing the scope of the save/load to just the analysis parameters. This allows users to restore the analysis state by just repeating the analysis itself. Such an approach is slower but is more comprehensive with respect to obtaining a fully functional state. It is easier to reason about as we don't have to worry about mixing up results from different versions (#45), and we avoid problems with back-compatibility when migrating old result formats into more recent versions of the `State` objects.

The second component of this shift involves saving the results into something that can be reloaded into the "explore-only" version of the application. This will allow users to explore pre-computed results without the strict obligation of reproducing the analysis UI. Importantly. the analysis UI does not need to be tied down by back-compatibility with old results, because those results are only relevant to the explore-only mode; and given that the explore mode doesn't do much, its contracts with its inputs are inherently looser, so back-compatibility is less of an issue there. 

In particular, I am thinking of saving the results into an **alabaster**-based SCE that contains many (but not all) results from various steps. This can be downloaded as a Zip/tarball or saved to an ArtifactDB backend. On reload, we open the "explore-only" mode and just treat it like any other SCE, populating the reddims and clusters and such. Now we don't have to care about changes to `colData` names, how the % variance per PC is encoded, etc., because the explore mode doesn't care either.

**Comment by LTLA** [comment]
This change has been implemented, though the existing `loadAnalysis()` and related functionality has been left in so that we can softly deprecate the old paradigm. @jkanche We should probably add banners on **kana** to indicate deprecation if someone tries to load a kana file, and to redirect them to re-save configuration/results in the new world.

**Comment by jkanche** [comment]
Or we continue to host the current version of kana as a legacy option for old datasets
